/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReadingsRouteImport } from './routes/readings'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WordsWordRouteImport } from './routes/words.$word'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingsRoute = ReadingsRouteImport.update({
  id: '/readings',
  path: '/readings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsWordRoute = WordsWordRouteImport.update({
  id: '/words/$word',
  path: '/words/$word',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/readings': typeof ReadingsRoute
  '/review': typeof ReviewRoute
  '/vocabulary': typeof VocabularyRoute
  '/words/$word': typeof WordsWordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/readings': typeof ReadingsRoute
  '/review': typeof ReviewRoute
  '/vocabulary': typeof VocabularyRoute
  '/words/$word': typeof WordsWordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/readings': typeof ReadingsRoute
  '/review': typeof ReviewRoute
  '/vocabulary': typeof VocabularyRoute
  '/words/$word': typeof WordsWordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/readings'
    | '/review'
    | '/vocabulary'
    | '/words/$word'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/readings' | '/review' | '/vocabulary' | '/words/$word'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/readings'
    | '/review'
    | '/vocabulary'
    | '/words/$word'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ReadingsRoute: typeof ReadingsRoute
  ReviewRoute: typeof ReviewRoute
  VocabularyRoute: typeof VocabularyRoute
  WordsWordRoute: typeof WordsWordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readings': {
      id: '/readings'
      path: '/readings'
      fullPath: '/readings'
      preLoaderRoute: typeof ReadingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/$word': {
      id: '/words/$word'
      path: '/words/$word'
      fullPath: '/words/$word'
      preLoaderRoute: typeof WordsWordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ReadingsRoute: ReadingsRoute,
  ReviewRoute: ReviewRoute,
  VocabularyRoute: VocabularyRoute,
  WordsWordRoute: WordsWordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
